
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    adapter: postgresql
    encoding: unicode
    database: dianaOnRails_development
    username: ian
    password: 1708
    host: localhost
    port: 5432


test:
  <<: *default
  database: dianaOnRails_test

#
production:
  <<: *default
  database: dianaOnRails_production
  username: dianaOnRails
  password: <%= ENV['DIANAONRAILS_DATABASE_PASSWORD'] %>
